import { useCallback,useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Image, Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { useLocalSearchParams,useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../providers/AuthProvider';
import { supabase } from '../lib/supabase';

export default function Community(){
 const {id}=useLocalSearchParams();const r=useRouter();const {user}=useAuth();const [community,setCommunity]=useState(null);const [member,setMember]=useState(null);const [members,setMembers]=useState(0);const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async(pull=false)=>{setLoading(!pull);setError('');const [c,m,mc,p]=await Promise.all([supabase.from('communities').select('id,name,slug,description,is_private,creator_id').eq('id',id).single(),supabase.from('community_members').select('role,status').eq('community_id',id).eq('user_id',user?.id||'').maybeSingle(),supabase.from('community_members').select('*',{count:'exact',head:true}).eq('community_id',id).eq('status','active'),supabase.from('posts').select('id,content,created_at,profiles:author_id(display_name,username,avatar_url)').eq('community_id',id).order('created_at',{ascending:false}).limit(30)]);if(c.error){setError(c.error.message)}else{setCommunity(c.data);setMember(m.data);setMembers(mc.count||0);setPosts(p.data||[])}setLoading(false)},[id,user?.id]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><Text>Loading community…</Text></View></SafeAreaView>;
 const join=async()=>{if(!user||busy)return;setBusy(true);const status=community.is_private?'pending':'active';const {error:e}=await supabase.from('community_members').upsert({community_id:id,user_id:user.id,status,role:'member'});if(e)setError(e.message);else setMember({status,role:'member'});setBusy(false);}; const leave=async()=>{if(!user||busy)return;setBusy(true);const {error:e}=await supabase.from('community_members').delete().eq('community_id',id).eq('user_id',user.id);if(e)setError(e.message);else setMember(null);setBusy(false);};
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={false} onRefresh={()=>load(true)}/>} contentContainerStyle={s.content}><Pressable onPress={()=>r.back()}><Text style={s.back}>← Back</Text></Pressable><View style={s.hero}><Text style={s.eyebrow}>COMMUNITY</Text><Text style={s.title}>{community?.name}</Text><Text style={s.meta}>{members} active member{members===1?'':'s'} · {posts.length} recent post{posts.length===1?'':'s'} · {community?.is_private?'Private':'Public'}</Text><Text style={s.desc}>{community?.description||'No description yet.'}</Text>{!member?<Pressable onPress={join} style={s.join}><Text style={s.joinText}>{busy?'Joining…':community?.is_private?'Request to join':'Join community'}</Text></Pressable>:member.status==='pending'?<Text style={s.member}>Request pending</Text>:<View style={s.actions}><Text style={s.member}>You’re a member</Text><Pressable onPress={leave} style={s.leave}><Text style={s.leaveText}>{busy?'Leaving…':'Leave'}</Text></Pressable></View>}</View><Text style={s.section}>Community posts</Text>{posts.length===0?<View style={s.empty}><Text style={s.h}>No posts yet</Text><Text style={s.p}>Posts shared with this community will appear here.</Text></View>:posts.map(p=><Pressable key={p.id} onPress={()=>r.push({pathname:'/post',params:{id:p.id}})} style={s.post}><View style={s.postHead}>{p.profiles?.avatar_url?<Image source={{uri:p.profiles.avatar_url}} style={s.postAvatar}/>:<View style={s.postAvatarFallback}><Text style={s.postAvatarText}>{(p.profiles?.display_name||p.profiles?.username||'M').charAt(0).toUpperCase()}</Text></View>}<Text style={s.author}>{p.profiles?.display_name||p.profiles?.username||'Member'}</Text></View><Text style={s.text}>{p.content||''}</Text><Text style={s.time}>{new Date(p.created_at).toLocaleString()}</Text></Pressable>)}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},content:{padding:20,paddingBottom:35},center:{flex:1,alignItems:'center',justifyContent:'center'},back:{fontSize:13,color:'#696974'},hero:{marginTop:20,padding:20,borderRadius:22,backgroundColor:'#17171b'},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.5,color:'#b5a9ff'},title:{marginTop:8,fontSize:28,fontWeight:'760',color:'#fff'},meta:{marginTop:8,fontSize:11,color:'#b9bac3'},desc:{marginTop:14,fontSize:13,lineHeight:20,color:'#e8e8ec'},join:{marginTop:18,minHeight:44,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},joinText:{fontSize:12,fontWeight:'750',color:'#17171b'},member:{fontSize:12,fontWeight:'700',color:'#d8d3ff'},actions:{marginTop:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},leave:{paddingHorizontal:12,paddingVertical:8,borderRadius:10,borderWidth:1,borderColor:'#4a4a52'},leaveText:{fontSize:11,fontWeight:'700',color:'#fff'},postHead:{flexDirection:'row',alignItems:'center',gap:10},postAvatar:{width:34,height:34,borderRadius:17},postAvatarFallback:{width:34,height:34,borderRadius:17,backgroundColor:'#17171b',alignItems:'center',justifyContent:'center'},postAvatarText:{fontSize:12,fontWeight:'800',color:'#fff'},section:{marginTop:28,fontSize:18,fontWeight:'750',color:'#17171b'},empty:{marginTop:15,padding:20,borderWidth:1,borderColor:'#e8e8ec',borderRadius:16,alignItems:'center'},h:{fontSize:16,fontWeight:'700'},p:{marginTop:6,textAlign:'center',fontSize:12,color:'#696974'},post:{paddingVertical:16,borderBottomWidth:1,borderBottomColor:'#e8e8ec'},author:{fontSize:11,fontWeight:'750',color:'#6546f5'},text:{marginTop:6,fontSize:14,lineHeight:21,color:'#17171b'},time:{marginTop:6,fontSize:10,color:'#8a8a94'},error:{marginTop:15,fontSize:12,color:'#a33'}});
