import { useCallback,useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Image, Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { useLocalSearchParams,useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../providers/AuthProvider';
import { supabase } from '../lib/supabase';

export default function Community(){
 const {id}=useLocalSearchParams();const r=useRouter();const {user}=useAuth();const [community,setCommunity]=useState(null);const [member,setMember]=useState(null);const [members,setMembers]=useState(0);const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [posting,setPosting]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async(pull=false)=>{setLoading(!pull);setError('');const [c,m,mc,p]=await Promise.all([supabase.from('communities').select('id,name,slug,description,is_private,creator_id').eq('id',id).single(),supabase.from('community_members').select('role,status').eq('community_id',id).eq('user_id',user?.id||'').maybeSingle(),supabase.from('community_members').select('*',{count:'exact',head:true}).eq('community_id',id).eq('status','active'),supabase.from('posts').select('id,content,created_at,profiles:author_id(display_name,username,avatar_url)').eq('community_id',id).order('created_at',{ascending:false}).limit(30)]);if(c.error){setError(c.error.message)}else{setCommunity(c.data);setMember(m.data);setMembers(mc.count||0);setPosts(p.data||[])}setLoading(false)},[id,user?.id]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><Text>Loading community…</Text></View></SafeAreaView>;
 const join=async()=>{if(!user||busy)return;setBusy(true);const status=community.is_private?'pending':'active';const {error:e}=await supabase.from('community_members').upsert({community_id:id,user_id:user.id,status,role:'member'});if(e)setError(e.message);else setMember({status,role:'member'});setBusy(false);}; const leave=async()=>{if(!user||busy||community?.creator_id===user.id)return;setBusy(true);const {error:e}=await supabase.from('community_members').delete().eq('community_id',id).eq('user_id',user.id);if(e)setError(e.message);else setMember(null);setBusy(false);};
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={false} onRefresh={()=>load(true)}/>} contentContainerStyle={s.content}><Pressable onPress={()=>r.back()}><Text style={s.back}>← Back</Text></Pressable><View style={s.hero}><Text style={s.eyebrow}>COMMUNITY</Text><Text style={s.title}>{community?.name}</Text><Text style={s.meta}>{members} active member{members===1?'':'s'} · {posts.length} recent post{posts.length===1?'':'s'} · {community?.is_private?'Private':'Public'}</Text><Text style={s.desc}>{community?.description||'No description yet.'}</Text>{!member?<Pressable onPress={join} style={s.join}><Text style={s.joinText}>{busy?'Joining…':community?.is_private?'Request to join':'Join community'}</Text></Pressable>:member.status==='pending'?<Text style={s.member}>Request pending</Text>:<View style={s.actions}><Text style={s.member}>You’re a member</Text><Pressable onPress={leave} style={s.leave}><Text style={s.leaveText}>{busy?'Leaving…':'Leave'}</Text></Pressable></View>}</View><View style={s.postCtaRow}><Text style={s.section}>Community posts</Text>{member?.status==='active'&&<Pressable disabled={posting} onPress={()=>r.push({pathname:'/create',params:{communityId:id}})} style={s.postCta}><Text style={s.postCtaText}>＋ Post</Text></Pressable>}</View>{posts.length===0?<View style={s.empty}><Text style={s.h}>No posts yet</Text><Text style={s.p}>Posts shared with this community will appear here.</Text></View>:posts.map(p=><Pressable key={p.id} onPress={()=>r.push({pathname:'/post',params:{id:p.id}})} style={s.post}><View style={s.postHead}>{p.profiles?.avatar_url?<Image source={{uri:p.profiles.avatar_url}} style={s.postAvatar}/>:<View style={s.postAvatarFallback}><Text style={s.postAvatarText}>{(p.profiles?.display_name||p.profiles?.username||'M').charAt(0).toUpperCase()}</Text></View>}<Text style={s.author}>{p.profiles?.display_name||p.profiles?.username||'Member'}</Text></View><Text style={s.text}>{p.content||''}</Text><Text style={s.time}>{new Date(p.created_at).toLocaleString()}</Text></Pressable>)}{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>
}
undefined
