import {useCallback,useEffect,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {supabase} from '../lib/supabase';
import {useAuth} from '../providers/AuthProvider';

export default function Conversation(){
 const{id}=useLocalSearchParams(),{user}=useAuth(),router=useRouter(),[info,setInfo]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{if(!id||!user?.id)return;setLoading(true);const{data:c,error:ce}=await supabase.from('conversations').select('id,kind,title,conversation_members(user_id,request_status,profiles:user_id(id,username,display_name))').eq('id',id).maybeSingle();if(ce||!c){setError(ce?.message||'Conversation not found');setLoading(false);return}const me=(c.conversation_members||[]).find(x=>x.user_id===user.id);const other=(c.conversation_members||[]).find(x=>x.user_id!==user.id);setInfo({...c,me,other});if(me?.request_status==='accepted'){const{data:m,error:e}=await supabase.from('messages').select('id,conversation_id,sender_id,content,created_at,edited_at,deleted_at,profiles:sender_id(id,username,display_name)').eq('conversation_id',id).order('created_at',{ascending:true}).limit(200);if(e)setError(e.message);else{setMessages(m||[]);const unread=(m||[]).filter(x=>x.sender_id!==user.id&&!x.deleted_at);if(unread.length){const{data:reads}=await supabase.from('message_reads').select('message_id').eq('user_id',user.id).in('message_id',unread.map(x=>x.id));const seen=new Set((reads||[]).map(x=>x.message_id));const missing=unread.filter(x=>!seen.has(x.id)).map(x=>({message_id:x.id,user_id:user.id}));if(missing.length)await supabase.from('message_reads').insert(missing)}}}setLoading(false)},[id,user?.id]);
 useEffect(()=>{load();if(!id)return;const ch=supabase.channel('conversation-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+id},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[id,load]);
 const send=async()=>{const v=text.trim();if(!v||!info?.me||info.me.request_status!=='accepted'||sending)return;setSending(true);setError('');const{error:e}=await supabase.from('messages').insert({conversation_id:id,sender_id:user.id,content:v});if(e)setError(e.message);else setText('');setSending(false);if(!e)load()};
 const name=info?.other?.profiles?.display_name||info?.other?.profiles?.username||'Conversation';
 const accept=async()=>{const{error:e}=await supabase.from('conversation_members').update({request_status:'accepted'}).eq('conversation_id',id).eq('user_id',user.id);if(e)setError(e.message);else load()};
 return <SafeAreaView style={s.safe}><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.name}>{name}</Text>{info?.other?.profiles?.username&&<Text style={s.handle}>@{info.other.profiles.username}</Text>}</View></View>{error&&<Text style={s.err}>{error}</Text>}{loading?<Text style={s.muted}>Loading conversation…</Text>:info?.me?.request_status==='pending'?<View style={s.request}><Text style={s.h}>Message request</Text><Text style={s.p}>Accept this request to read and send messages.</Text><Pressable onPress={accept} style={s.accept}><Text style={s.wh}>Accept request</Text></Pressable></View>:<><ScrollView contentContainerStyle={s.messages}>{messages.map(m=><View key={m.id} style={[s.bubble,m.sender_id===user.id?s.mine:s.theirs]}><Text style={[s.bt,m.sender_id===user.id&&s.mbt]}>{m.deleted_at?'Message deleted':m.content}</Text><Text style={[s.time,m.sender_id===user.id&&s.mbt]}>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View>)}</ScrollView><View style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Write a message…" placeholderTextColor="#999" style={s.input}/><Pressable disabled={sending} onPress={send} style={s.send}><Text style={s.wh}>Send</Text></Pressable></View></>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},head:{padding:15,borderBottomWidth:1,borderBottomColor:'#e8e8ec',flexDirection:'row',alignItems:'center',gap:13},back:{fontSize:30,color:'#17171b'},name:{fontSize:14,fontWeight:'750',color:'#17171b'},handle:{fontSize:10,color:'#696974'},err:{padding:12,color:'#9e2f2f',fontSize:12},muted:{padding:20,color:'#696974'},messages:{padding:16,gap:9},bubble:{maxWidth:'78%',padding:10,borderRadius:14},mine:{alignSelf:'flex-end',backgroundColor:'#17171b'},theirs:{alignSelf:'flex-start',backgroundColor:'#f1f1f4'},bt:{fontSize:13,lineHeight:19,color:'#17171b'},mbt:{color:'#fff'},time:{marginTop:4,fontSize:9,color:'#777'},request:{margin:20,padding:20,borderWidth:1,borderColor:'#e8e8ec',borderRadius:18,backgroundColor:'#f7f7f9'},h:{fontSize:18,fontWeight:'700',color:'#17171b'},p:{marginTop:7,fontSize:13,lineHeight:19,color:'#696974'},accept:{marginTop:16,alignSelf:'flex-start',paddingHorizontal:14,height:36,borderRadius:10,backgroundColor:'#17171b',justifyContent:'center'},wh:{color:'#fff',fontSize:10,fontWeight:'700'},composer:{padding:10,borderTopWidth:1,borderTopColor:'#e8e8ec',flexDirection:'row',gap:8},input:{flex:1,minHeight:42,maxHeight:90,paddingHorizontal:12,borderWidth:1,borderColor:'#e8e8ec',borderRadius:12,color:'#17171b'},send:{paddingHorizontal:14,borderRadius:11,backgroundColor:'#6546f5',justifyContent:'center'}});
