import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../providers/AuthProvider';
import { supabase } from '../lib/supabase';

export default function CreateCommunity(){
 const r=useRouter();const {user}=useAuth();const[name,setName]=useState('');const[description,setDescription]=useState('');const[privateCommunity,setPrivateCommunity]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const create=async()=>{if(!user||!name.trim()||busy)return;setBusy(true);setError('');const slug=name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50);if(slug.length<3){setError('Choose a longer community name.');setBusy(false);return;}if(description.trim().length>500){setError('Keep the description under 500 characters.');setBusy(false);return;}const {data,error:e}=await supabase.from('communities').insert({name:name.trim(),slug,description:description.trim()||null,creator_id:user.id,is_private:privateCommunity}).select('id').single();if(e){setError(e.message);setBusy(false);return;}await supabase.from('community_members').upsert({community_id:data.id,user_id:user.id,role:'admin',status:'active'});setBusy(false);r.replace({pathname:'/community',params:{id:data.id}});};
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable disabled={busy} onPress={()=>r.back()}><Text style={s.cancel}>Cancel</Text></Pressable><Text style={s.title}>Create community</Text><Pressable disabled={!name.trim()||busy} onPress={create}><Text style={[s.save,(!name.trim()||busy)&&s.disabled]}>{busy?'Creating…':'Create'}</Text></Pressable></View><Text style={s.eyebrow}>BELONG</Text><Text style={s.heading}>Give people a place to belong.</Text><Text style={s.lead}>Create a real shared space for conversation and community posts.</Text><Text style={s.label}>Community name</Text><TextInput value={name} onChangeText={setName} style={s.input} placeholder="e.g. Nairobi Creators" placeholderTextColor="#8a8a94"/><Text style={s.label}>Description</Text><TextInput value={description} onChangeText={setDescription} style={[s.input,s.area]} multiline maxLength={500} placeholder="What is this community about?" placeholderTextColor="#8a8a94"/><Text style={s.counter}>{description.length}/500</Text><Pressable onPress={()=>setPrivateCommunity(v=>!v)} style={s.toggle}><View style={[s.box,privateCommunity&&s.boxOn]}>{privateCommunity&&<Text style={s.check}>✓</Text>}</View><View style={{flex:1}}><Text style={s.toggleTitle}>Private community</Text><Text style={s.toggleText}>Members must be approved before joining.</Text></View></Pressable>{!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#060B12},content:{padding:20},header:{height:55,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#182533',marginBottom:28},title:{fontSize:16,fontWeight:'750',color:'#E9EEF4'},cancel:{fontSize:13,color:'#7F8D9D'},save:{fontSize:13,fontWeight:'750',color:'#7F96B0'},disabled:{opacity:.35},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.5,color:'#6F82A0'},heading:{marginTop:9,fontSize:28,lineHeight:34,fontWeight:'760',letterSpacing:-1,color:'#E9EEF4'},lead:{marginTop:8,fontSize:13,lineHeight:20,color:'#A9B6C5'},label:{fontSize:11,fontWeight:'700',color:'#696974',marginBottom:7,marginTop:23},input:{height:48,paddingHorizontal:13,borderWidth:1,borderColor:'#182533',borderRadius:13,fontSize:14,color:'#E9EEF4',backgroundColor:'#0A121C'},area:{height:125,textAlignVertical:'top',paddingTop:13},counter:{marginTop:5,textAlign:'right',fontSize:10,color:'#718096'},toggle:{flexDirection:'row',gap:12,alignItems:'center',marginTop:24,paddingVertical:12},box:{width:24,height:24,borderRadius:7,borderWidth:1,borderColor:'#2A3A4B',alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:'#253447',borderColor:'#17171b'},check:{color:'#F4F6F8',fontWeight:'800'},toggleTitle:{fontSize:13,fontWeight:'700',color:'#17171b'},toggleText:{marginTop:3,fontSize:11,color:'#696974'},error:{marginTop:18,fontSize:12,color:'#C88491'}});
