import { useEffect, useMemo, useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../lib/supabase';
import * as ImagePicker from 'expo-image-picker';
import { useVideoPlayer, VideoView } from 'expo-video';
import { useAuth } from '../providers/AuthProvider';
import AppIcon from '../components/AppIcon';
import { getImageUrl } from '../lib/imageUrl';

const C={bg:'#060B12',panel:'#0A121C',panel2:'#0E1824',line:'#182533',text:'#E9EEF4',muted:'#7F8D9D',blue:'#4B78A8',violet:'#4A3F78'};

export default function Create(){
 const r=useRouter(); const params=useLocalSearchParams(); const communityId=useMemo(()=>Array.isArray(params.communityId)?params.communityId[0]:params.communityId,[params.communityId]); const {user,profile}=useAuth(); const {width}=useWindowDimensions(); const desktop=Platform.OS==='web'&&width>=1000;
 const [text,setText]=useState(''); const [visibility,setVisibility]=useState('public'); const [community,setCommunity]=useState(null); const [communityError,setCommunityError]=useState(''); const [showVisibility,setShowVisibility]=useState(false); const [showOptions,setShowOptions]=useState(null); const [location,setLocation]=useState(''); const [taggedPeople,setTaggedPeople]=useState([]); const [feeling,setFeeling]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [video,setVideo]=useState(null); const [photos,setPhotos]=useState([]); const [uploadingVideo,setUploadingVideo]=useState(false);
 const displayName=profile?.display_name||user?.email?.split('@')[0]||'Your profile';
 const loadCommunity=async()=>{if(!communityId||!user?.id)return;const [{data:c,error:ce},{data:m,error:me}]=await Promise.all([supabase.from('communities').select('id,name,is_private').eq('id',communityId).single(),supabase.from('community_members').select('status').eq('community_id',communityId).eq('user_id',user.id).maybeSingle()]);if(ce||me||!m?.status||m.status!=='active'){setCommunityError('You need to be an active member to post in this community.');return;}setCommunity(c);};
 useEffect(()=>{loadCommunity();},[communityId,user?.id]);
 const pickVideo=async()=>{if(uploadingVideo||saving)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Permission required','Allow Freetopia to access your videos.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['videos'],allowsEditing:false,quality:1,videoExportPreset:ImagePicker.VideoExportPreset.Passthrough,videoMaxDuration:600});if(result.canceled||!result.assets?.[0])return;const asset=result.assets[0];if(asset.fileSize&&asset.fileSize>100*1024*1024){Alert.alert('Video too large','Please choose a video smaller than 100 MB.');return;}setVideo(asset);setError('');};
 const removeVideo=()=>{if(saving||uploadingVideo)return;setVideo(null);};
 const pickPhotos=async()=>{if(uploadingVideo||saving)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Permission required','Allow Freetopia to access your photos.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:false,allowsMultipleSelection:true,selectionLimit:10,quality:1});if(result.canceled||!result.assets?.length)return;const next=result.assets.filter(a=>!a.fileSize||a.fileSize<=15*1024*1024).slice(0,10);if(next.length<result.assets.length)Alert.alert('Some photos skipped','Each photo must be smaller than 15 MB.');setPhotos(next);setVideo(null);setError('');};
 const removePhoto=uri=>setPhotos(current=>current.filter(photo=>photo.uri!==uri));
 const uploadPhoto=async(asset,postId,index)=>{const extension=(asset.fileName?.split('.').pop()||asset.mimeType?.split('/')[1]||'jpg').toLowerCase();const path=user.id+'/'+postId+'/'+Date.now()+'-'+index+'.'+extension;const body=await fetch(asset.uri).then(res=>res.arrayBuffer());const{error:uploadError}=await supabase.storage.from('post-media').upload(path,body,{contentType:asset.mimeType||'image/jpeg',upsert:false});if(uploadError)throw uploadError;const{data:urlData}=supabase.storage.from('post-media').getPublicUrl(path);const{error:mediaError}=await supabase.from('post_media').insert({post_id:postId,storage_path:path,media_type:'image',width:asset.width||null,height:asset.height||null,sort_order:index,processing_status:'ready',playback_url:null,thumbnail_path:urlData.publicUrl});if(mediaError){await supabase.storage.from('post-media').remove([path]);throw mediaError;}return path;};

 const submit=async()=>{const content=text.trim();if((!content&&!video&&!photos.length)||!user||saving||uploadingVideo)return;setSaving(true);setError('');if(communityId && !community){setError(communityError||'This community is not available for posting.');setSaving(false);return;}let mediaPath=null;let thumbnailUrl=null;let postId=null;let mediaRowId=null;let uploadedPhotoPaths=[];try{const{data:post,error:e}=await supabase.from('posts').insert({author_id:user.id,content:content||null,visibility,community_id:communityId||null}).select('id').single();if(e)throw e;postId=post.id;if(video){setUploadingVideo(true);const{data:signData,error:signError}=await supabase.functions.invoke('cloudinary-video-upload',{body:{post_id:post.id}});if(signError)throw signError;if(signData?.error)throw new Error(signData.error);mediaPath='cloudinary:'+signData.public_id;thumbnailUrl=signData.thumbnail_url||null;const{data:mediaRow,error:mediaError}=await supabase.from('post_media').insert({post_id:post.id,storage_path:mediaPath,media_type:'video',width:video.width||null,height:video.height||null,duration_seconds:video.duration?video.duration/1000:null,sort_order:0,processing_status:'uploading',playback_url:null,thumbnail_path:thumbnailUrl}).select('id').single();if(mediaError)throw mediaError;mediaRowId=mediaRow.id;const form=new FormData();form.append('file',{uri:video.uri,name:video.fileName||('freetopia-'+Date.now()+'.mp4'),type:video.mimeType||'video/mp4'});form.append('api_key',signData.api_key);form.append('timestamp',String(signData.timestamp));form.append('public_id',signData.public_id);form.append('eager',signData.eager);form.append('eager_async','true');form.append('eager_notification_url',signData.eager_notification_url);form.append('context',signData.context);form.append('return_delete_token','true');form.append('signature',signData.signature);const response=await fetch(signData.upload_url,{method:'POST',body:form});const uploadResult=await response.json().catch(()=>null);if(!response.ok||uploadResult?.error)throw new Error(uploadResult?.error?.message||'Video upload failed.');await supabase.from('post_media').update({processing_status:'processing'}).eq('id',mediaRowId).eq('processing_status','uploading');}if(photos.length){for(let i=0;i<photos.length;i++)uploadedPhotoPaths.push(await uploadPhoto(photos[i],post.id,i));}setVideo(null);setPhotos([]);r.replace(communityId?{pathname:'/community',params:{id:communityId}}:'/home');}catch(e){if(mediaPath&&mediaPath.indexOf('cloudinary:')!==0)await supabase.storage.from('post-media').remove([mediaPath]);if(uploadedPhotoPaths.length)await supabase.storage.from('post-media').remove(uploadedPhotoPaths);if(mediaRowId)await supabase.from('post_media').delete().eq('id',mediaRowId);if(postId)await supabase.from('posts').delete().eq('id',postId);setError(e?.message||'Could not publish your post.');}finally{setUploadingVideo(false);setSaving(false);}};
 const setVis=v=>{setVisibility(v);setShowVisibility(false);};
 const chooseOption=(type,value)=>{if(type==='location')setLocation(value);if(type==='feeling')setFeeling(value);if(type==='tag')setTaggedPeople(value?[value]:[]);setShowOptions(null);};
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}>
  {desktop?<DesktopHeader router={r} profile={profile}/>:<MobileHeader router={r} saving={saving} canPost={!!text.trim()||!!video||!!photos.length} submit={submit}/>}
  <View style={[s.layout,desktop&&s.desktopLayout]}>
   <ScrollView style={s.scroll} contentContainerStyle={s.scrollContent} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <View style={s.identity}><Avatar profile={profile} displayName={displayName}/><View style={s.identityText}><Text style={s.name}>{displayName}</Text>{profile?.username&&<Text style={s.handle}>@{profile.username}</Text>}</View><View style={s.visibilityWrap}>
      <Pressable onPress={()=>setShowVisibility(v=>!v)} style={s.visibilityButton}><AppIcon name="globe" size={15} color={C.muted}/><Text style={s.visibilityText}>{visibility==='public'?'Public':'Followers'}</Text><AppIcon name="chevron-down" size={14} color={C.muted}/></Pressable>
      {showVisibility&&<View style={s.visibilityMenu}><Pressable onPress={()=>setVis('public')} style={s.menuRow}><Text style={s.menuTitle}>Public</Text><Text style={s.menuSub}>Anyone can see this post</Text></Pressable><Pressable onPress={()=>setVis('followers')} style={s.menuRow}><Text style={s.menuTitle}>Followers</Text><Text style={s.menuSub}>Only your followers can see it</Text></Pressable></View>}
    </View></View>
    {community&&<View style={s.communityContext}><Text style={s.communityContextLabel}>COMMUNITY</Text><Text style={s.communityContextName}>{community.name}</Text><Text style={s.communityContextHint}>This post will be shared with this community.</Text></View>}
    <TextInput autoFocus multiline maxLength={5000} value={text} onChangeText={setText} placeholder={"What's on your mind, "+displayName.split(' ')[0]+"?"} placeholderTextColor="#8093AA" style={s.input}/>
    <View style={s.actionGrid}><Pressable onPress={pickPhotos} disabled={saving||uploadingVideo} style={[s.action,photos.length&&s.actionActive]}><AppIcon name="photo" size={18}/><Text style={s.actionText}>{photos.length?photos.length+" photo"+(photos.length===1?"":"s")+" added":"Photo"}</Text></Pressable><Pressable onPress={pickVideo} disabled={saving||uploadingVideo} style={[s.action,video&&s.actionActive]}><AppIcon name="video" size={18}/><Text style={s.actionText}>{uploadingVideo?'Uploading…':video?'Video added':'Video'}</Text></Pressable><Action icon="poll" label="Poll"/><Action icon="write" label="Write" active/></View>
    {video?<VideoPreview asset={video} onRemove={removeVideo}/>:photos.length?<PhotoPreview assets={photos} onRemove={removePhoto}/>:<View style={s.mediaBox}><Text style={s.mediaIcon}>▧</Text><Text style={s.mediaTitle}>Photos and videos</Text><Text style={s.mediaSub}>Choose photos or videos directly from your device.</Text></View>}
    <OptionRow icon="location" title="Add location" subtitle={location||'Optional'} onPress={()=>setShowOptions('location')}/><OptionRow icon="profile" title="Tag people" subtitle={taggedPeople.length?`@${taggedPeople[0]}`:'Mention friends'} onPress={()=>setShowOptions('tag')}/><OptionRow icon="users" title="Add to community" subtitle={community?.name||'Share with a community'} onPress={()=>setShowOptions('community')}/><OptionRow icon="spark" title="Feeling / Activity" subtitle={feeling||'How are you feeling?'} onPress={()=>setShowOptions('feeling')}/>
    <OptionRow icon="settings" title="Privacy" subtitle={visibility==='public'?'Public':'Followers'} onPress={()=>setShowVisibility(v=>!v)} />
    {showOptions==='location'&&<ChoicePanel title="Add location" choices={['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret']} onChoose={v=>chooseOption('location',v)} />}
    {showOptions==='tag'&&<TagPeoplePanel userId={user?.id} onChoose={v=>chooseOption('tag',v)} />}
    {showOptions==='community'&&<CommunityPicker userId={user?.id} selectedId={communityId} onChoose={v=>{setCommunity(v);setCommunityError('');setShowOptions(null);}} />}
    {showOptions==='feeling'&&<ChoicePanel title="Feeling / Activity" choices={['Feeling happy','Feeling excited','Feeling grateful','Feeling motivated','Watching a movie','Listening to music','Working out','Travelling']} onChoose={v=>chooseOption('feeling',v)} />}
    {!!error&&<View style={s.error}><Text style={s.errorText}>{error}</Text></View>}
    <Pressable disabled={(!text.trim()&&!video&&!photos.length)||saving||uploadingVideo} onPress={submit} style={[s.submit,((!text.trim()&&!video&&!photos.length)||saving||uploadingVideo)&&s.submitDisabled]}><Text style={s.submitText}>{saving?'Posting…':'Post  →'}</Text></Pressable>
   </ScrollView>
   {desktop&&<DesktopRail/>}
  </View>
 </KeyboardAvoidingView></SafeAreaView>;
}
function DesktopHeader({router,profile}){return <View style={s.top}><View style={s.brand}><Image source={require('../public/brand/freetopia-mark.png')} style={s.logo}/><Text style={s.brandText}>Freetopia</Text></View><View style={s.topActions}><Pressable onPress={()=>router.push('/notifications')}><AppIcon name="bell" size={18}/></Pressable><Pressable onPress={()=>router.push('/messages')}><AppIcon name="message" size={18}/></Pressable><Pressable onPress={()=>router.push('/profile')}><View style={s.topAvatar}>{profile?.avatar_url?<Image source={{uri:getImageUrl(profile.avatar_url,{width:160,height:160,quality:100})}} style={s.topAvatarImage}/>:<Text style={s.topAvatarText}>{(profile?.display_name||profile?.username||'F').charAt(0).toUpperCase()}</Text>}</View></Pressable></View></View>}
function MobileHeader({router,saving,canPost,submit}){return <View style={s.mobileTop}><Pressable onPress={()=>router.back()}><AppIcon name="arrow-left" size={18}/></Pressable><Image source={require('../public/brand/freetopia-mark.png')} style={s.logo}/><Text style={s.mobileBrand}>Freetopia</Text><View style={{flex:1}}/><Pressable disabled={!canPost||saving} onPress={submit} style={[s.headerPost,(!canPost||saving)&&s.submitDisabled]}><Text style={s.headerPostText}>{saving?'…':'Post'}</Text></Pressable></View>}
function Avatar({profile,displayName}){return profile?.avatar_url?<Image source={{uri:getImageUrl(profile.avatar_url,{width:600,height:600,quality:100})}} style={s.avatar}/>:<View style={s.avatar}><Text style={s.avatarText}>{displayName.charAt(0).toUpperCase()}</Text></View>}
function Action({icon,label,active}){return <View style={[s.action,active&&s.actionActive]}><Text style={s.actionIcon}>{icon}</Text><Text style={s.actionText}>{label}</Text></View>}
function PhotoPreview({assets,onRemove}){return <View style={s.photoPreview}>{assets.map(asset=><View key={asset.uri} style={s.photoItem}><Image source={{uri:asset.uri}} style={s.photoImage}/><Pressable onPress={()=>onRemove(asset.uri)} style={s.photoRemove}><Text style={s.photoRemoveText}>×</Text></Pressable></View>)}</View>}
function VideoPreview({asset,onRemove}){const player=useVideoPlayer(asset?.uri||null,p=>{p.loop=true;p.muted=true;p.play();});return <View style={s.videoPreview}><VideoView player={player} style={s.videoView} nativeControls={false} contentFit="cover" surfaceType={Platform.OS==='android'?'textureView':undefined}/><View style={s.videoBadge}><Text style={s.videoBadgeText}>VIDEO · {asset?.width||0}×{asset?.height||0}</Text><Pressable onPress={onRemove} style={s.videoRemove}><Text style={s.videoRemoveText}>Remove</Text></Pressable></View></View>}
function OptionRow({icon,title,subtitle,onPress}){return <Pressable onPress={onPress} style={s.optionRow}><View style={s.optionIcon}><AppIcon name={icon} size={17} color={C.muted}/></View><View style={s.optionCopy}><Text style={s.optionTitle}>{title}</Text><Text style={s.optionSub}>{subtitle}</Text></View><AppIcon name="chevron-right" size={15} color={C.muted}/></Pressable>}
function ChoicePanel({title,choices,onChoose}){return <View style={s.choicePanel}><View style={s.choiceHead}><Text style={s.choiceTitle}>{title}</Text><Pressable onPress={()=>onChoose('')}><Text style={s.choiceClose}>×</Text></Pressable></View>{choices.map(x=><Pressable key={x} onPress={()=>onChoose(x)} style={s.choiceRow}><Text style={s.choiceText}>{x}</Text><AppIcon name="chevron-right" size={14} color={C.muted}/></Pressable>)}</View>}
function TagPeoplePanel({userId,onChoose}){const [people,setPeople]=useState([]);const [q,setQ]=useState('');useEffect(()=>{let active=true;(async()=>{const {data}=await supabase.from('profiles').select('username,display_name').neq('id',userId).order('display_name').limit(30);if(active)setPeople(data||[]);})();return()=>{active=false};},[userId]);const filtered=people.filter(p=>(p.display_name||p.username||'').toLowerCase().includes(q.toLowerCase()));return <View style={s.choicePanel}><View style={s.choiceHead}><Text style={s.choiceTitle}>Tag people</Text><Pressable onPress={()=>onChoose('')}><Text style={s.choiceClose}>×</Text></Pressable></View><TextInput value={q} onChangeText={setQ} placeholder="Search people" placeholderTextColor={C.muted} style={s.choiceSearch}/>{filtered.slice(0,8).map(p=><Pressable key={p.username} onPress={()=>onChoose(p.username)} style={s.choiceRow}><View style={s.choiceAvatar}><Text style={s.choiceAvatarText}>{(p.display_name||p.username||'F')[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.choiceText}>{p.display_name||p.username}</Text><Text style={s.choiceSub}>@{p.username}</Text></View></Pressable>)}</View>}
function CommunityPicker({userId,selectedId,onChoose}){const [list,setList]=useState([]);useEffect(()=>{let active=true;(async()=>{const {data}=await supabase.from('communities').select('id,name,is_private').order('created_at',{ascending:false}).limit(30);if(active)setList(data||[]);})();return()=>{active=false};},[]);return <View style={s.choicePanel}><View style={s.choiceHead}><Text style={s.choiceTitle}>Add to community</Text><Pressable onPress={()=>onChoose(null)}><Text style={s.choiceClose}>×</Text></Pressable></View>{list.map(x=><Pressable key={x.id} onPress={()=>onChoose(x)} style={[s.choiceRow,x.id===selectedId&&s.choiceSelected]}><View style={{flex:1}}><Text style={s.choiceText}>{x.name}</Text><Text style={s.choiceSub}>{x.is_private?'Private community':'Public community'}</Text></View>{x.id===selectedId?<AppIcon name="check" size={15} color={C.text}/>:<AppIcon name="chevron-right" size={14} color={C.muted}/>}</Pressable>)}{!list.length&&<Text style={s.choiceSub}>No communities available.</Text>}</View>}
function DesktopRail(){return <View style={s.rail}><View style={s.railCard}><Text style={s.railTitle}>Suggested Communities</Text>{['Tech & Innovation','Fitness & Health','Music Vibes','Business & Finance','Travel Diaries'].map(x=><View key={x} style={s.suggest}><View style={s.suggestIcon}><Text>✦</Text></View><View style={{flex:1}}><Text style={s.suggestName}>{x}</Text><Text style={s.suggestMeta}>Discover shared interests</Text></View><Text style={s.joinText}>Join</Text></View>)}</View><View style={s.railCard}><Text style={s.railTitle}>Trending Topics</Text>{['#Mindset','#Tech','#Fitness','#Business','#Freetopia'].map(x=><View key={x} style={s.topic}><Text style={s.topicIcon}>#</Text><Text style={s.topicText}>{x}</Text></View>)}</View><View style={s.promo}><Text style={s.promoBrand}>◈ Freetopia</Text><Text style={s.promoTitle}>Better people. Bigger dreams.</Text><Pressable style={s.promoButton}><Text style={s.promoButtonText}>Join Now  →</Text></Pressable></View></View>}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.bg},flex:{flex:1},top:{height:68,borderBottomWidth:1,borderBottomColor:C.line,flexDirection:'row',alignItems:'center',paddingHorizontal:22},brand:{flexDirection:'row',alignItems:'center',gap:9},logo:{width:34,height:34},brandText:{color:C.text,fontSize:18,fontWeight:'850'},topActions:{marginLeft:'auto',flexDirection:'row',alignItems:'center',gap:20},topIcon:{color:C.text,fontSize:20},topAvatar:{width:32,height:32,borderRadius:16,backgroundColor:'#2B415B',alignItems:'center',justifyContent:'center'},topAvatarText:{color:'#E9EEF4',fontWeight:'900'},topAvatarImage:{width:32,height:32,borderRadius:16},
 mobileTop:{height:64,flexDirection:'row',alignItems:'center',paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.line},back:{fontSize:36,color:C.text,lineHeight:36,marginRight:10},mobileBrand:{fontSize:18,fontWeight:'850',color:C.text,marginLeft:7},headerPost:{height:38,minWidth:70,paddingHorizontal:18,borderRadius:20,backgroundColor:'#344A62',alignItems:'center',justifyContent:'center'},headerPostText:{color:'#fff',fontWeight:'850',fontSize:13},
 layout:{flex:1},desktopLayout:{flexDirection:'row',maxWidth:1200,alignSelf:'center',width:'100%'},scroll:{flex:1},scrollContent:{padding:18,paddingBottom:45,maxWidth:760,width:'100%',alignSelf:'center'},identity:{flexDirection:'row',alignItems:'center',paddingVertical:12},identityText:{marginLeft:11,flex:1},avatar:{width:46,height:46,borderRadius:23,backgroundColor:'#223850',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#58718D'},avatarText:{color:'#fff',fontWeight:'900',fontSize:17},name:{color:C.text,fontSize:15,fontWeight:'850'},handle:{color:C.muted,fontSize:11,marginTop:2},communityContext:{marginTop:4,marginBottom:6,padding:11,borderRadius:10,borderWidth:1,borderColor:'#21415F',backgroundColor:'#081726'},communityContextLabel:{color:'#7890A8',fontSize:8,fontWeight:'850',letterSpacing:1.2},communityContextName:{color:C.text,fontSize:12,fontWeight:'800',marginTop:3},communityContextHint:{color:C.muted,fontSize:9,marginTop:2},
 visibilityWrap:{position:'relative'},visibilityButton:{height:34,paddingHorizontal:11,borderRadius:9,backgroundColor:C.panel2,borderWidth:1,borderColor:'#193652',flexDirection:'row',alignItems:'center',gap:6},globe:{color:'#B7C9DE',fontSize:12},visibilityText:{color:'#D8E4F1',fontSize:10,fontWeight:'750'},chevron:{color:'#A6B9CE',fontSize:14},visibilityMenu:{position:'absolute',right:0,top:40,width:190,zIndex:20,borderWidth:1,borderColor:C.line,borderRadius:10,backgroundColor:'#0A1828',overflow:'hidden'},menuRow:{padding:12,borderBottomWidth:1,borderBottomColor:C.line},menuTitle:{color:C.text,fontSize:11,fontWeight:'800'},menuSub:{color:C.muted,fontSize:8,marginTop:3},
 input:{minHeight:145,fontSize:20,lineHeight:29,color:C.text,textAlignVertical:'top',paddingTop:10},actionGrid:{flexDirection:'row',gap:10,marginVertical:8},action:{flex:1,height:48,borderRadius:10,backgroundColor:C.panel2,borderWidth:1,borderColor:'#183450',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},actionActive:{borderColor:'#34485E',backgroundColor:'#111B28'},actionIcon:{color:'#7EA5FF',fontSize:17},actionText:{color:'#D7E2EF',fontSize:10,fontWeight:'750'},
 mediaBox:{height:150,borderWidth:1,borderColor:'#21415F',borderStyle:'dashed',borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:'#08111B',marginTop:9},photoPreview:{marginTop:9,flexDirection:'row',flexWrap:'wrap',gap:8},photoItem:{width:'31.8%',aspectRatio:1,borderRadius:10,overflow:'hidden',backgroundColor:'#02060B',borderWidth:1,borderColor:C.line,position:'relative'},photoImage:{width:'100%',height:'100%'},photoRemove:{position:'absolute',right:6,top:6,width:25,height:25,borderRadius:13,backgroundColor:'#08111B',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#50657B'},photoRemoveText:{color:'#fff',fontSize:18,lineHeight:20},videoPreview:{marginTop:9,height:260,borderRadius:12,overflow:'hidden',backgroundColor:'#02060B',borderWidth:1,borderColor:C.line},videoView:{width:'100%',height:'100%'},videoBadge:{position:'absolute',left:10,right:10,bottom:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},videoBadgeText:{color:'#E9EEF4',fontSize:8,fontWeight:'800',backgroundColor:'#08111B',paddingHorizontal:8,paddingVertical:5,borderRadius:8},videoRemove:{backgroundColor:'#1A1016',borderWidth:1,borderColor:'#6B3041',paddingHorizontal:9,paddingVertical:5,borderRadius:8},videoRemoveText:{color:'#FFB1BE',fontSize:8,fontWeight:'800'},mediaIcon:{fontSize:30,color:'#64778B'},mediaTitle:{color:'#D8E4F2',fontSize:12,fontWeight:'800',marginTop:8},mediaSub:{color:C.muted,fontSize:9,marginTop:4,textAlign:'center',paddingHorizontal:20},
 optionRow:{minHeight:64,borderBottomWidth:1,borderBottomColor:C.line,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:2},choicePanel:{marginTop:8,marginBottom:4,borderWidth:1,borderColor:'#21415F',borderRadius:11,backgroundColor:'#091522',overflow:'hidden'},choiceHead:{height:46,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.line},choiceTitle:{color:C.text,fontSize:12,fontWeight:'800'},choiceClose:{color:C.muted,fontSize:22,lineHeight:22},choiceRow:{minHeight:46,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:C.line},choiceSelected:{backgroundColor:'#101F32'},choiceText:{color:C.text,fontSize:10,fontWeight:'700'},choiceSub:{color:C.muted,fontSize:8,marginTop:2},choiceSearch:{height:38,margin:8,borderWidth:1,borderColor:'#1B334D',borderRadius:8,paddingHorizontal:10,color:C.text,fontSize:10},choiceAvatar:{width:28,height:28,borderRadius:14,backgroundColor:'#243B55',alignItems:'center',justifyContent:'center'},choiceAvatarText:{color:C.text,fontSize:10,fontWeight:'800'},optionIcon:{width:30,alignItems:'center'},optionIconText:{color:'#D2DEEA',fontSize:22},optionCopy:{flex:1},optionTitle:{color:C.text,fontSize:12,fontWeight:'650'},optionSub:{color:C.muted,fontSize:9,marginTop:3},rowChevron:{color:'#A8BCD0',fontSize:25},optionBlock:{minHeight:64,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.line},error:{padding:10,borderRadius:9,backgroundColor:'#26111A',borderWidth:1,borderColor:'#6B3041',marginTop:12},errorText:{color:'#FFB1BE',fontSize:10},submit:{height:46,borderRadius:23,backgroundColor:C.violet,alignItems:'center',justifyContent:'center',marginTop:14},submitDisabled:{opacity:.4},submitText:{color:'#fff',fontSize:13,fontWeight:'900'},
 rail:{width:290,padding:18,paddingLeft:0,gap:12},railCard:{borderWidth:1,borderColor:C.line,borderRadius:11,backgroundColor:C.panel,padding:13},railTitle:{color:C.text,fontSize:13,fontWeight:'850',marginBottom:9},suggest:{minHeight:51,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,borderBottomColor:C.line},suggestIcon:{width:33,height:33,borderRadius:9,backgroundColor:'#1A2A39',alignItems:'center',justifyContent:'center'},suggestName:{color:C.text,fontSize:9,fontWeight:'800'},suggestMeta:{color:C.muted,fontSize:7,marginTop:2},joinText:{color:'#B8C8FF',fontSize:8,fontWeight:'850'},topic:{height:40,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:C.line},topicIcon:{width:28,height:28,borderRadius:8,backgroundColor:'#17345A',color:'#B9D4FF',textAlign:'center',textAlignVertical:'center',fontWeight:'900'},topicText:{color:'#D4DFEB',fontSize:10,fontWeight:'700'},promo:{borderRadius:11,borderWidth:1,borderColor:'#263244',backgroundColor:'#111B28',padding:16,minHeight:145},promoBrand:{color:'#DCE7FF',fontSize:13,fontWeight:'900'},promoTitle:{color:'#fff',fontSize:15,fontWeight:'850',marginTop:15,lineHeight:20},promoButton:{height:35,borderRadius:18,backgroundColor:C.blue,alignItems:'center',justifyContent:'center',marginTop:15},promoButtonText:{color:'#fff',fontSize:9,fontWeight:'850'}
});