import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!;
const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const cloud=Deno.env.get("CLOUDINARY_CLOUD_NAME");
const apiKey=Deno.env.get("CLOUDINARY_API_KEY");
const secret=Deno.env.get("CLOUDINARY_API_SECRET");
const webhook=Deno.env.get("CLOUDINARY_WEBHOOK_URL");
async function sha1(value:string){const d=await crypto.subtle.digest("SHA-1",new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});const auth=req.headers.get("authorization")||"";const token=auth.replace(/^Bearer\s+/i,"");const admin=createClient(url,service);const {data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)return new Response("Unauthorized",{status:401});if(!cloud||!apiKey||!secret||!webhook)return new Response(JSON.stringify({error:"Cloudinary is not configured."}),{status:503,headers:{"content-type":"application/json"}});const body=await req.json().catch(()=>null);const postId=body?.post_id;if(!postId)return new Response(JSON.stringify({error:"post_id is required"}),{status:400});const {data:post}=await admin.from("posts").select("id,author_id").eq("id",postId).single();if(!post||post.author_id!==userData.user.id)return new Response("Forbidden",{status:403});const timestamp=Math.floor(Date.now()/1000);const publicId=`freetopia/posts/${userData.user.id}/${postId}-${crypto.randomUUID().replaceAll("-","")}`;const eager="sp_hd,f_m3u8";const context=`media_id=${postId}`;const signature=await sha1(`context=${context}&eager=${eager}&eager_async=true&eager_notification_url=${webhook}&public_id=${publicId}&return_delete_token=true&timestamp=${timestamp}${secret}`);return new Response(JSON.stringify({cloud_name:cloud,api_key:apiKey,timestamp,public_id:publicId,eager,eager_notification_url:webhook,context,signature,upload_url:`https://api.cloudinary.com/v1_1/${cloud}/video/upload`,playback_url:`https://res.cloudinary.com/${cloud}/video/upload/sp_hd/${publicId}.m3u8`,\n    thumbnail_url:`https://res.cloudinary.com/${cloud}/video/upload/so_0,w_720,q_auto/${publicId}.jpg`}),{headers:{"content-type":"application/json"}});});