import { useCallback,useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../../lib/supabase';

export default function Communities(){
 const r=useRouter();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const {data,e}=await supabase.from('communities').select('id,name,slug,description,is_private').order('created_at',{ascending:false}).limit(50);if(e)setError(e.message);else setItems(data||[]);setLoading(false)},[]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.content}><View style={s.top}><View><Text style={s.eyebrow}>BELONG</Text><Text style={s.title}>Communities</Text><Text style={s.lead}>Shared spaces for interests, conversations, and people.</Text></View><Pressable onPress={()=>r.push('/create-community')} style={s.create}><Text style={s.createText}>Create</Text></Pressable></View>{loading?<View style={s.empty}><Text style={s.h}>Loading communities…</Text></View>:error?<View style={s.empty}><Text style={s.h}>Couldn’t load communities</Text><Text style={s.p}>{error}</Text></View>:items.length===0?<View style={s.empty}><Text style={s.big}>◎</Text><Text style={s.h}>No communities yet</Text><Text style={s.p}>Create the first real shared space.</Text><Pressable onPress={()=>r.push('/create-community')} style={s.btn}><Text style={s.btnText}>Create a community</Text></Pressable></View>:items.map(x=><Pressable key={x.id} onPress={()=>r.push({pathname:'/community',params:{id:x.id}})} style={s.card}><View style={s.icon}><Text style={s.iconText}>{x.name.charAt(0).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.desc}>{x.description||'No description yet.'}</Text><Text style={s.meta}>{x.is_private?'Private':'Public'} · @{x.slug}</Text></View></Pressable>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},content:{padding:20,paddingBottom:30},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.5,color:'#6546f5'},title:{marginTop:8,fontSize:31,fontWeight:'760',letterSpacing:-1.1,color:'#17171b'},lead:{marginTop:8,fontSize:14,lineHeight:21,color:'#696974'},create:{paddingHorizontal:13,paddingVertical:9,borderRadius:11,backgroundColor:'#17171b'},createText:{color:'#fff',fontSize:11,fontWeight:'750'},empty:{marginTop:25,padding:22,borderWidth:1,borderColor:'#e8e8ec',borderRadius:18,alignItems:'center'},big:{fontSize:32,color:'#6546f5'},h:{marginTop:8,fontSize:17,fontWeight:'700',color:'#17171b'},p:{marginTop:7,textAlign:'center',fontSize:13,lineHeight:20,color:'#696974'},btn:{marginTop:17,minHeight:44,paddingHorizontal:18,borderRadius:13,backgroundColor:'#17171b',justifyContent:'center'},btnText:{color:'#fff',fontSize:13,fontWeight:'700'},card:{flexDirection:'row',gap:13,alignItems:'center',paddingVertical:17,borderBottomWidth:1,borderBottomColor:'#e8e8ec'},icon:{width:48,height:48,borderRadius:15,backgroundColor:'#17171b',alignItems:'center',justifyContent:'center'},iconText:{color:'#fff',fontSize:18,fontWeight:'750'},name:{fontSize:15,fontWeight:'750',color:'#17171b'},desc:{marginTop:4,fontSize:12,lineHeight:18,color:'#696974'},meta:{marginTop:5,fontSize:10,color:'#8a8a94'}});
