import {useCallback,useState} from 'react';
import {useFocusEffect} from '@react-navigation/native';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {supabase} from '../../lib/supabase';
import {useAuth} from '../../providers/AuthProvider';

export default function Messages(){
 const{user}=useAuth(),router=useRouter(),[tab,setTab]=useState('Messages'),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{if(!user?.id)return;setLoading(true);const{data,error:e}=await supabase.from('conversations').select('id,kind,title,created_at,conversation_members(user_id,request_status,is_archived,profiles:user_id(id,username,display_name))').order('created_at',{ascending:false});if(e)setError(e.message);else setItems((data||[]).map(c=>{const m=c.conversation_members||[];return{...c,me:m.find(x=>x.user_id===user.id),other:m.find(x=>x.user_id!==user.id)}}).filter(c=>c.me));setLoading(false)},[user?.id]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const change=async(c,p)=>{const{error:e}=await supabase.from('conversation_members').update(p).eq('conversation_id',c.id).eq('user_id',user.id);if(e)setError(e.message);else load()};
 const rows=items.filter(c=>tab==='Requests'?c.me.request_status==='pending':tab==='Archived'?c.me.request_status==='accepted'&&c.me.is_archived:tab==='Messages'?c.me.request_status==='accepted'&&!c.me.is_archived:false);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.head}><View><Text style={s.k}>CONNECT</Text><Text style={s.title}>Messages</Text></View><Pressable onPress={()=>router.push('/new-message')} style={s.new}><Text style={s.wh}>New</Text></Pressable></View><Text style={s.lead}>Private conversations without the clutter.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{['Messages','Requests','Communities','Archived'].map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.sel]}><Text style={[s.tabt,tab===x&&s.selt]}>{x}</Text></Pressable>)}</ScrollView>{error&&<Text style={s.err}>{error}</Text>}{loading&&<Text style={s.muted}>Loading conversations…</Text>}{!loading&&tab==='Communities'&&<Empty text="Community messaging is not connected yet."/>}{!loading&&tab!=='Communities'&&!rows.length&&<Empty text={tab==='Requests'?'No message requests.':'No conversations yet.'}/>} {!loading&&rows.map(c=><Row key={c.id} c={c} tab={tab} open={()=>router.push({pathname:'/conversation',params:{id:c.id}})} accept={()=>change(c,{request_status:'accepted'})} decline={()=>change(c,{request_status:'declined'})} archive={()=>change(c,{is_archived:!c.me.is_archived})}/>)}</ScrollView></SafeAreaView>}
function Empty({text}){return <View style={s.empty}><Text style={s.icon}>✉</Text><Text style={s.h}>{text}</Text><Text style={s.p}>Real conversations will appear here.</Text></View>}
function Row({c,tab,open,accept,decline,archive}){const p=c.other?.profiles,n=p?.display_name||p?.username||c.title||'Conversation';return <View style={s.row}><Pressable onPress={open} style={s.main}><View style={s.avatar}><Text style={s.avt}>{n[0]?.toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{n}</Text>{p?.username&&<Text style={s.handle}>@{p.username}</Text>}{tab==='Requests'&&<Text style={s.pending}>Message request</Text>}</View></Pressable>{tab==='Requests'?<View style={s.actions}><Pressable onPress={accept} style={s.accept}><Text style={s.wh}>Accept</Text></Pressable><Pressable onPress={decline} style={s.decline}><Text style={s.bt}>Decline</Text></Pressable></View>:<Pressable onPress={archive} style={s.small}><Text style={s.bt}>{tab==='Archived'?'Unarchive':'Archive'}</Text></Pressable>}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},content:{padding:20},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},k:{fontSize:10,fontWeight:'800',letterSpacing:1.5,color:'#6546f5'},title:{marginTop:8,fontSize:31,fontWeight:'760',color:'#17171b'},lead:{marginTop:8,fontSize:14,lineHeight:21,color:'#696974'},new:{paddingHorizontal:15,height:36,borderRadius:11,backgroundColor:'#17171b',justifyContent:'center'},wh:{color:'#fff',fontSize:10,fontWeight:'700'},tabs:{gap:7,paddingVertical:18},tab:{paddingHorizontal:13,height:34,borderRadius:17,borderWidth:1,borderColor:'#e8e8ec',justifyContent:'center'},sel:{backgroundColor:'#17171b'},tabt:{fontSize:11,color:'#696974'},selt:{color:'#fff'},err:{padding:12,color:'#9e2f2f'},muted:{color:'#696974'},empty:{marginTop:10,padding:24,borderWidth:1,borderColor:'#e8e8ec',borderRadius:18,alignItems:'center',backgroundColor:'#f7f7f9'},icon:{fontSize:25,color:'#6546f5'},h:{marginTop:12,fontSize:17,fontWeight:'700',color:'#17171b'},p:{marginTop:7,fontSize:13,color:'#696974'},row:{flexDirection:'row',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderBottomColor:'#e8e8ec',gap:8},main:{flex:1,flexDirection:'row',alignItems:'center',gap:10},avatar:{width:44,height:44,borderRadius:22,backgroundColor:'#17171b',alignItems:'center',justifyContent:'center'},avt:{color:'#fff',fontWeight:'700'},name:{fontSize:13,fontWeight:'700',color:'#17171b'},handle:{fontSize:11,color:'#696974'},pending:{fontSize:10,color:'#6546f5'},actions:{gap:5},accept:{padding:9,backgroundColor:'#17171b',borderRadius:8},decline:{padding:9,borderWidth:1,borderColor:'#e8e8ec',borderRadius:8},small:{padding:8,borderWidth:1,borderColor:'#e8e8ec',borderRadius:8},bt:{fontSize:10,color:'#17171b',fontWeight:'700'}});
