import { useCallback, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../providers/AuthProvider';
import { supabase } from '../../lib/supabase';

export default function Profile(){
 const r=useRouter(); const {user,profile,signOut}=useAuth(); const [counts,setCounts]=useState({following:0,followers:0});
 useFocusEffect(useCallback(()=>{let active=true;(async()=>{if(!user)return;const [a,b]=await Promise.all([supabase.from('follows').select('*',{count:'exact',head:true}).eq('follower_id',user.id).eq('status','accepted'),supabase.from('follows').select('*',{count:'exact',head:true}).eq('following_id',user.id).eq('status','accepted')]);if(active)setCounts({following:a.count||0,followers:b.count||0});})();return()=>{active=false}},[user]));
 const name=profile?.display_name||user?.email?.split('@')[0]||'Your profile'; const handle=profile?.username?'@'+profile.username:''; const initial=name.charAt(0).toUpperCase();
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.cover}/><View style={s.avatar}><Text style={s.avatarText}>{initial}</Text></View><View style={s.actions}><Pressable onPress={()=>r.push('/edit-profile')} style={s.outline}><Text style={s.outlineText}>Edit profile</Text></Pressable><Pressable onPress={()=>r.push('/settings')} style={s.outline}><Text style={s.outlineText}>Settings</Text></Pressable></View><Text style={s.name}>{name}</Text>{!!handle&&<Text style={s.handle}>{handle}</Text>}<Text style={s.bio}>{profile?.bio||'Add a bio to tell people a little about yourself.'}</Text><View style={s.stats}><Text><Text style={s.stat}>{counts.following}</Text> following</Text><Text><Text style={s.stat}>{counts.followers}</Text> followers</Text></View><View style={s.tabs}><Text style={s.activeTab}>Posts</Text><Text>Replies</Text><Text>Media</Text><Text>Likes</Text></View><View style={s.empty}><Text style={s.h}>Nothing here yet</Text><Text style={s.p}>Your posts and conversations will live here.</Text></View><Pressable onPress={signOut} style={s.signOut}><Text style={s.signOutText}>Sign out</Text></Pressable></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},content:{paddingBottom:30},cover:{height:145,backgroundColor:'#17171b'},avatar:{marginTop:-30,marginLeft:20,width:70,height:70,borderRadius:35,borderWidth:4,borderColor:'#fff',backgroundColor:'#17171b',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:24,fontWeight:'750'},actions:{flexDirection:'row',justifyContent:'flex-end',gap:8,paddingHorizontal:20,marginTop:-32},outline:{height:38,paddingHorizontal:13,borderWidth:1,borderColor:'#e8e8ec',borderRadius:12,justifyContent:'center'},outlineText:{fontSize:11,fontWeight:'700',color:'#17171b'},name:{marginTop:19,paddingHorizontal:20,fontSize:22,fontWeight:'750',color:'#17171b'},handle:{paddingHorizontal:20,marginTop:3,fontSize:12,color:'#8a8a94'},bio:{paddingHorizontal:20,marginTop:10,fontSize:13,lineHeight:20,color:'#696974'},stats:{flexDirection:'row',gap:20,paddingHorizontal:20,marginTop:14},stat:{fontWeight:'750',color:'#17171b'},tabs:{flexDirection:'row',justifyContent:'space-around',marginTop:24,paddingVertical:15,borderBottomWidth:1,borderTopWidth:1,borderColor:'#e8e8ec'},activeTab:{fontWeight:'750',color:'#17171b'},empty:{margin:20,padding:22,borderWidth:1,borderColor:'#e8e8ec',borderRadius:18,alignItems:'center'},h:{fontSize:17,fontWeight:'700',color:'#17171b'},p:{marginTop:7,textAlign:'center',fontSize:13,lineHeight:20,color:'#696974'},signOut:{marginHorizontal:20,minHeight:46,borderWidth:1,borderColor:'#f0cccc',borderRadius:13,alignItems:'center',justifyContent:'center'},signOutText:{fontSize:13,fontWeight:'700',color:'#a33'}});